---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-test-php-fpm-monitor
  namespace: example-test
  labels:
    app: example-test
spec:
  endpoints:
  - interval: 30s
    port: metrics-php-fpm #matching deployment ports name
  selector:
    matchLabels:
      app: example-test